### PR TITLE
Jonas Pull Request

### PR DESCRIPTION
**Pull request by japelbaum**

### CODE REVIEW

**Comment by chabowski** [comment]
Hi @japelbaum - I did not yet merge the PR because GitHub shows we a conflict with the master repo. The file were I am getting the conflict for is "MAIN-SBP-CSP-UpdateInfra.xml". Isn't that the old file we created back in spring? The reason might be the file is already existing in the repo ... 

In the PR, you also committed a new xml file "MAIN-SBP-UpdateInfra.xml". Are these two files different documents?

Thanks for clarification!

**Comment by chabowski** [comment]
Hi @japelbaum @mfriesenegger 
I discussed your PR with my colleague Thomas Schraitle. We think the reason for the conflict might be that you Jona forked the official SBP master at a certain point in time, to create the doc (back in spring). Then you did a pull request at time being. I merged your changes into the official SBP repo, and from there, I worked on the paper in the official SBP repo, and implemented some here changes. When you retook the work on the paper, you did probably not "refresh" your old fork of the official SBP repo via a "git pull"? This means you implemented your new changes into an "older" version of the paper (because your fork did not contain my changes). And now we might have this conflict with that file. 

Can you confirm that you did not "update" your first fork of the original SBP repo via git pull? If that is the case ... 

To fix the issue, you need to try the following: 

1) Retract your Pull Request

2) In your own japelbaum repo, enter the following command
`git remote add upstream https://github.com/SUSE/suse-best-practices.git`

3) After that, enter the following command
`$ git remote -v`

You should see the following output: 
`origin git@github.com:japelbaum/suse-best-practices.git (fetch)
origin git@github.com:japelbaum/suse-best-practices.git (push)
upstream https://github.com/SUSE/suse-best-practices.git (fetch)
upstream https://github.com/SUSE/suse-best-practices.git (push)`

4) Now, in your own japelbaum repo, do the following:
`$ git checkout master`
`$ git pull upstream`

5) Now you better open a new feature branch, and add all your changes from the previous PR
`$ git checkout -b feature/NAME`
# Add your changes to feature branch

6) Now you can commit your changes
`$ git commit` 
# <-- enter your commit message 

7) Now push your command
`$ git push -u origin BRANCHNAME`

and do a Pull Request (or Git should give you a message what to do) 

This hopefully solves the problem. 

But if you encounter any problem, I am sure my colleague Thomas Schraitle (you find him on Rocket Chat) is willing to help you. Unfortunately I am not working on Fridays, but Thomas is the Git Master anyways ;-) ... 

Keeping my fingers crossed!

**Comment by japelbaum** [comment]
Fixing issues

**Comment by japelbaum** [comment]
Hey Meike,

Thank you for the help in getting this sorted.

As you correctly said I did not refresh  the old fork. That being said, Mike helped me to figure this out.

You should now have a pull request with no conflicts.

That being said, it seems that travis-ci does not build the file correctly, while we where able to build it correctly.

Thank you!

Jona Apelbaum
Cloud Solutions Architect
SUSE CSP EMEA
+34 690 11 96 97
jona.apelbaum@suse.com<mailto:jona.apelbaum@suse.com>


Jona Apelbaum
Cloud Solutions Architect
SUSE CSP EMEA
+34 690 11 96 97
jona.apelbaum@suse.com<mailto:jona.apelbaum@suse.com>

**Comment by japelbaum** [comment]
Meike,

I was able to do a new pull request and it looks like it goes through the ci/cd check now. So we are good 😊

Thanks for the help!

Cheers

Jona

Jona Apelbaum
Cloud Solutions Architect
SUSE CSP EMEA
+34 690 11 96 97
jona.apelbaum@suse.com<mailto:jona.apelbaum@suse.com>

From: Jona Apelbaum
Sent: 08 October 2020 23:35
To: 'SUSE/suse-best-practices' <reply@reply.github.com>; SUSE/suse-best-practices <suse-best-practices@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Mike Friesenegger <mikef@suse.com>
Subject: RE: [SUSE/suse-best-practices] Jonas Pull Request (#100)

Hey Meike,

Thank you for the help in getting this sorted.

As you correctly said I did not refresh  the old fork. That being said, Mike helped me to figure this out.

You should now have a pull request with no conflicts.

That being said, it seems that travis-ci does not build the file correctly, while we where able to build it correctly.

Thank you!

Jona Apelbaum
Cloud Solutions Architect
SUSE CSP EMEA
+34 690 11 96 97
jona.apelbaum@suse.com<mailto:jona.apelbaum@suse.com>


Jona Apelbaum
Cloud Solutions Architect
SUSE CSP EMEA
+34 690 11 96 97
jona.apelbaum@suse.com<mailto:jona.apelbaum@suse.com>

**Pull request closed without merging**
