### PR TITLE
SAP HANA SR Perf-Opt Guide for SLE12

### PR DESCRIPTION
**Pull request by fmherschel**
This guide should replace the former setup-guide which has been shipped to the document
pages using the "old" publishing way.
Once we get this document out it should replace the following document:
https://documentation.suse.com/sbp/all/
-> "SAP Applications on SUSE Linux Enterprise 12"
-> "Setting up a SAP HANA SR Performance Optimized Infrastructure (SLES for SAP Applications 12 SP1)"

### CODE REVIEW

**Comment by chabowski** [comment]
Hi Fabian @fmherschel - I think I know what the issue is, but I can work on it only on Monday. Hope this is okay. 

Thanks!
Meike

**Comment by fmherschel** [comment]
> Hi Fabian @fmherschel - I think I know what the issue is, but I can work on it only on Monday. Hope this is okay.
> 
> Thanks!
> Meike

Hi Meike, @chabowski 

if we (Bernd or I) could improve something in our adoc source file which avoids
this problem I would be keen to learn about that improvement.

Regards
Fabian

**Comment by chabowski** [comment]
Hi Fabian, 

the main issue is that the DC file needs some more ADOC variables/attributes. Without them, the elements simpara and listitems are not converted correctly for the xml file we need to build the docs. 

For SBPs, the DC file should have the following information: 
---------------------------------------------------------------
MAIN="Title.adoc"

ADOC_TYPE="article"

ADOC_POST="yes"

ADOC_ATTRIBUTES="--attribute docdate=yyyy-mm-dd"

# stylesheets
STYLEROOT="/usr/share/xml/docbook/stylesheet/suse2013-sbp-ns"

XSLTPARAM="--stringparam publishing.series=sbp"

# DRAFT=yes
ROLE="sbp"
PROFROLE="sbp"
------------------------

- The variable ADOC_POST="yes" ensures the correct conversion of certain adoc markups to xml elements.
- The ADOC_ATTRIBUTES with the docdate ensures the correct *publishing* date (NOT build date) is given inside the document. 
- Using the SBP stylesheet ensures the correct layout. 


Stefan found an additional issue: 
The image caption "Planning the installation is essential for a successful SAP HANA cluster setup." needs the correct markup for an image caption.
I am not 100 percent sure what that is, but I think if you want to add a real caption, it should be: 
caption="Figure x: blablabla"
and if you want to add a title to the image it should be:
.blablabla 
or 
title="blablabla"

If you could fix that, that would be marvelous!

Thanks very much,
Meike

**Comment by fmherschel** [comment]
> Stefan found an additional issue:
> The image caption "Planning the installation is essential for a successful SAP HANA cluster setup." needs the correct markup for an image caption.
> I am not 100 percent sure what that is, but I think if you want to add a real caption, it should be:
> caption="Figure x: blablabla"
> and if you want to add a title to the image it should be:
> .blablabla
> or
> title="blablabla"

"Planning ..." was never intendet to be a image caption it should be the next paragraph.

I alsoways markup image captions like:

.\<Caption\>
image::\<whatever\>

**Comment by fmherschel** [comment]
Found it - there was a left-over old anchor (\[\[\<anchortext\>\]\]). Removed it - now travis passes.

**Comment by chabowski** [comment]
@fmherschel Hi Fabian, after merging your PR into the SBP master, I have done some edits to the document (according to our style guide, and after a run through style checker and spell checker). If you want to have the latest version on your private repo, I think you should rebase it.

**Pull request merged**
