### PR TITLE
SAPHanaSR-ScaleOut multi-target ERP style

### PR DESCRIPTION
**Pull request by lpinne**
added new SAPHanaSR-ScaleOut multi-target ERP style setup guide

### CODE REVIEW

**Review by chabowski — COMMENTED** [review]
Hi @lpinne could you please make sure that also the docinfo file is renamed to what the DC file shows? In this case, it would be : 
adoc/SLES4SAP-hana-scaleout-multitarget-perfopt-15-docinfo.xml
 Thank you!

**Comment by lpinne** [comment]
Hi Meike,
I have changed the filename locally, checked by daps2docker, and pushed the filename change.
My branch is clean.
Need to check why the filename did not make it up.
Regards,
Lars

**Comment by lpinne** [comment]
Hi Meike,
local daps2docker does not need that xml, so I missed that change.
Thank you!
Regards,
Lars

**Review by chabowski — COMMENTED** [review]
Thank you Lars :-) !!

**Pull request merged**
