### PR TITLE
Usc caasp4

### PR DESCRIPTION
**Pull request by uschairer**

### CODE REVIEW

**Comment by chabowski** [comment]
Hi @uschairer - Travis CI checks failed due to wrong elements. I will have a look at it on Monday (as I am not working on Fridays) and hopefully I can fix it and merge the PR. Thanks very much!

**Comment by chabowski** [comment]
@uschairer Hi again Ulrich. One question: did you create *new* DC, MAIN, and docinfo files for the CaaSP4 version - or did you just rename the old CaaSP3 paper and kind of updated that one?

**Comment by uschairer** [comment]
> @uschairer Hi again Ulrich. One question: did you create _new_ DC, MAIN, and docinfo files for the CaaSP4 version - or did you just rename the old CaaSP3 paper and kind of updated that one?

Honestly I do not really understand what happened here. I fear I accidently created this pull request to the master.
Maybe it would be best to discard this one and hopefully I will do things better next time?
Thanks.

**Comment by uschairer** [comment]
We cann discuss this on Monday in RC?

**Comment by chabowski** [comment]
Hi @uschairer Of course we can discuss. But at least I need @sknorr for the discussion ;-). I have opened a new RC channel where we can discuss on Monday. Talk to you then!

**Pull request closed without merging**
