### PR TITLE
Add guide for wordpress on lamp stack on sles.

### PR DESCRIPTION
**Pull request by jamesongithub**
@ab-mohamed @kevinayres @stephenmogg @petersatsuse please review, ty.

you can use the rich text version [here](https://github.com/SUSE/suse-best-practices/pull/221/files?short_path=07b1a93#diff-07b1a934895e030caa60617afd21d26375208c4ac34fa629f137271cd4902941)

### CODE REVIEW

**Comment by chabowski** [comment]
Hi James @jamesongithub - thanks for the PR. Do you still need to do content changes/additions to the document? If yes, I would wait with merging, if no, I will merge tomorrow morning and do a review of the document. Just let me know. Thanks very much - Meike

**Comment by jamesongithub** [comment]
hi @chabowski, ready for merging. thank you!

**Comment by chabowski** [comment]
Hi @jamesongithub I am out this week, but will work on it next week Monday. Did you also incorporate the proposals from Peter? Thank you very much!
Meike

**Comment by jamesongithub** [comment]
HI @chabowski yes along w/ some feedback from Stephen. 

Next week will be fine. thank you!

**Comment by chabowski** [comment]
@jamesongithub Hi James, the document is merged to the SBP repo, reviewed and edited from a doc writing point of view. If you want to do another check, now is the time. Please let me know if you want to have more changes, or if we should publish the document tomorrow. Thanks very much!

**Comment by jamesongithub** [comment]
will take another look. thanks!

**Pull request merged**
