### PR TITLE
New Scale-Out document for AWS

### PR DESCRIPTION
**Pull request by gguifelixamz**
This a PR to create a new SUSE best practice and implementation guide for SAP HANA Scale Out in AWS.

It has been written based in the existing SAP HANA Scale Out doc but with changes related to AWS.

Please, let me know if changes are required before this can be published.

### CODE REVIEW

**Comment by chabowski** [comment]
@gguifelixamz  Hi Guilherme, 
the document looks good so far. I have merged it into the master repo, as our Travis checks were successful. I will now review and let you know if anything is unclear. Would you mind letting me know the exact job titles of you and your colleagues from AWS? Thanks very much! Meike

**Comment by gguifelixamz** [comment]
Hello @chabowski,

For job title you can use "SAP Specialist".

**Comment by chabowski** [comment]
Thank you!

**Comment by chabowski** [comment]
@gguifelixamz Hi Guilherme, 
the paper is published now under the SUSE Best Practice page at documentation: 
https://documentation.suse.com/sbp/all/
(see sections for SLES for SAP 12 SP4 and 15)

https://documentation.suse.com/sbp/all/pdf/SLES-SAP-hana-scaleOut-PerfOpt-12-AWS_color_en.pdf
https://documentation.suse.com/sbp/all/html/SLES-SAP-hana-scaleOut-PerfOpt-12-AWS/index.html

Please let me know if it looks good to you. Changes are always possible. 

Thanks very much and kind regards,
Meike

**Pull request merged**
