### PR TITLE
sql server getting started - remove code indents, data loading

### PR DESCRIPTION
**Pull request by jamesongithub**
@bwgartner have incorporated some of you feedback here.

### CODE REVIEW

**Comment by jamesongithub** [comment]
hi @chabowski thanks! what is the process to add this to the TRD section?

**Comment by chabowski** [comment]
Hi @jamesongithub,
content-wise, from your side, is the paper now ready to be published?
If so, we need to do some checks (style check, spell check, review), and if all is good and we do not have questions, I  will add the paper to the docserv config under the category TRD. After that, we will rebuild the repo, and with that, the paper will be published. 
How urgent is the paper - is there any time pressure? I am asking because this week, I am attending trainings ... 
Thanks!!

**Comment by jamesongithub** [comment]
Hi @chabowski. Thanks. Yes I think it's ready now for the checks and your reviews. The [toc2](https://github.com/SUSE/suse-best-practices/issues/162) directive didn't seem to work, but it's not required I guess. Next week would be fine. thanks!

**Comment by jamesongithub** [comment]
Good to add sql server guide this week?

**Comment by chabowski** [comment]
@jamesongithub Hi James, 
I will check and publish the paper beginning of next week. Currently I have 4 paid (by partners) papers in the loop which need to go public on March 15th, and a week with 10+ hours of training :-) ... Hope this is okay for you.
Thanks for your understanding, and kind regards,
Meike

**Pull request merged**
