### PR TITLE
Adopting SAP HA guides to cover native systemd integration

### PR DESCRIPTION
**Pull request by fmherschel**

### CODE REVIEW

**Comment by chabowski** [comment]
Hi @fmherschel thank you for the PR! I had a quick check of the commits and changes. So far all seems to be good. I will merge the PR, but iI would like to review and do some checks locally, and build the docs - and I will also have to adjust the DC files with the new dates for the content updates. As I am not working on Fridays, I will start with that on Monday. Do you have a deadline for publication? Is the timeframe of next week okay? Thank you!

**Comment by fmherschel** [comment]
Good evening @chabowski  :) I am fine with the schedule next week. We currently have no time-near time line. Sorry I completely for got to update the dates, Should I do that by my own?

**Comment by chabowski** [comment]
@fmherschel no worries I will update the DC files for the dates, as I will do a review of all docs anyway :-). Thanks again!

**Comment by chabowski** [comment]
@fmherschel @lpinne I have merged the PR into main and am currently working on some editorial updates and checks. As an example, we do not use capitalized section titles anymore, but according to our style guide we use sentence-style titles for a while now. I will update these things with new content updates. 

Also, I will take the opportunity of content updates to make important SEO changes to the file names. We do not use underscores in file names anymore, and we try to avoid capital letters in file names except for a few things such as marking the file type (DC or MAIN), the document type (SBP or TRD), and some main product name. This is for better search engine results and better findability. I've just started with these changes for the 5 documents contained in this PR. You will have to pull all changes into your repo clones. 

Please do not do any changes inside the main repo until I have finished these updates :-). 

Thank you!

**Pull request merged**
