### PR TITLE
Update region server section

### PR DESCRIPTION
**Pull request by mfriesenegger**

### CODE REVIEW

**Comment by mfriesenegger** [comment]
Can you give me a suggestion how to fix the xml so the CI check does not fail?

**Comment by chabowski** [comment]
> Can you give me a suggestion how to fix the xml so the CI check does not fail?

@mfriesenegger Hi Mike, 
first, I assume you pulled all the changed I made yesterday to have the most actual master repo?
Second, Travis is not happy about an element "bridgehead" being used - the error message says: "1057:18: error: element "bridgehead" not allowed here ... " Will try to find it.
Thanks!!

**Comment by chabowski** [comment]
Hi Mike, 
I have merged your PR despite the Travis check failure - but I think it is an easy one to be fixed, just an "element" or "tagging" issue.

**Comment by chabowski** [comment]
The issue was indeed the bridgehead element inside a procedure. I have fixed that with using the tag emphasis to highlight the example, instead of using a bridgehead title.

**Comment by mfriesenegger** [comment]
Thank you Meike!

**Pull request merged**
