### PR TITLE
New SBP document

### PR DESCRIPTION
**Pull request by ab-mohamed**
Hi, 

I have created the "Getting Started with SAP HANA High Availability Cluster Automation Operating on Azure" SBP guide that I would like to publish it. 

I prefixed all of the adoc files with "sap_hana_azure-" prefix and the DC file was added to the main repo directory.

### CODE REVIEW

**Comment by chabowski** [comment]
@sknorr Stefan would you mind having a look at this PR. Travis checks failed, Error message is: ERROR: AsciiDoc image directory /usr/src/app/adoc/images does not exist
Not sure exactly what the problem is. 

@ab-mohamed hey Ab, as long as the Travis check fails, I cannot merge. Let's see what Stefan recommends. 

Thanks!

**Comment by ab-mohamed** [comment]
Hi @chabowski, 

Could you please try it again?

I have removed the `imagedir` line.

**Comment by chabowski** [comment]
@ab-mohamed Travis test still fails ... @sknorr does by chance an obvious error / solution cross your mind ??

**Comment by sknorr** [comment]
Hey -- the issue is not (just) the images dir in the document itself, there is also a definition in the DC file. Could you try this as the DC file, please?

```
# MAIN file (mandatory)
MAIN="sap_hana_azure-main_document.adoc"

# Type
ADOC_TYPE="book"

# Turn on postprocessing
ADOC_POST="yes"

# Stylesheet directory
STYLEROOT="/usr/share/xml/docbook/stylesheet/suse2013-ns"

# Use DocBook 5 instead of GeekoDoc to circumvent issue with <authorinitials/>
DOCBOOK5_RNG_URI="file:///usr/share/xml/docbook/schema/rng/5.1/docbookxi.rnc"
```

**Comment by chabowski** [comment]
Thanks @sknorr  - I should have checked the DC file myself - appreciate it!

**Comment by ab-mohamed** [comment]
Hi @sknorr:

> # Use DocBook 5 instead of GeekoDoc to circumvent issue with <authorinitials/>
> DOCBOOK5_RNG_URI="file:///usr/share/xml/docbook/schema/rng/5.1/docbookxi.rnc"

Comparing my DC file with the proposed one, I found that you deleted the `ADOC_IMG_DIR` line which is clear for me and you added the `DOCBOOK5_RNG_URI` line. Could you please share more info about that line in order to be taken into consideration the next time I create another best practices document? 

> (Side note: SBP documents are usually ADOC_TYPE=article and it seems that format might also > be more suited to your document than ADOC_TYPE=book.)

I divided the BP guide into chapters for better maintenance from my side.

**Comment by sknorr** [comment]
> Comparing my DC file with the proposed one, I found that you deleted the ADOC_IMG_DIR line which is clear for me and you added the DOCBOOK5_RNG_URI line. Could you please share more info about that line in order to be taken into consideration the next time I create another best practices document?

Eh, sorry, yes of course! tldr: It helps avoid a Travis validation failure because of the way your author name is defined here.

Long version, I hope I am not over-explaining: DAPS handles AsciiDoc files the following way: It has `asciidoctor` generate a DocBook XML file and then from that DocBook XML intermediate generates the final output document. Since DocBook is a huge monster that allows basically possible and impossible use case, for most SUSE documentation, we are using a restricted version of the DocBook schema called GeekoDoc. It validates all the common things we use at SUSE and removes things we either don't use or think are unwise/unrenderable. GeekoDoc is enabled by default in Travis CI.

Now, AsciiDoctor generates DocBook according to its own rules and not necessarily according to what we defined as legal in GeekoDoc. The DOCBOOK5_RNG_URI line changes the XML document schema that is used for validating the document to the upstream unrestricted DocBook schema.

**Comment by ab-mohamed** [comment]
Thank you @sknorr for the elaboration. :)

**Comment by ab-mohamed** [comment]
@chabowski: I have committed the updated DC file.  Please try and let me know. :)

Best regards,
Ab

**Comment by sknorr** [comment]
So, apparently your DC file triggered a slightly esoteric bug in DAPS -- if there is no newline at the end of the file, the last line will be ignored. Going to report this now.

Do not that I just pushed to your branch (so I could see whether that also does the trick for Travis which it does) -- please make a `git pull` in your downstream repo before continuing to work on this.

**Comment by chabowski** [comment]
Thank you @sknorr that is indeed a strange bug, and I would never ever have "recognized" it ... So - we are through it now and nice Travis is now fine with it! THANKS Stefan and Ab!

**Comment by chabowski** [comment]
@ab-mohamed Hey Ab - your paper is now edited, please update your own repo and have a look. I will also send you a fresh PDF: Please have a look especially at the abstract at the beginning (before the TOC). Also, check the version number below the title. I have fixed several typos, style issues, smaller format things, and some smaller wording issues. Please let me know if all is okay and if we can publish as is or if you need to make changes. Thanks! Meike

**Pull request merged**
