### PR TITLE
Updated cloud automation quickstart for v7.0.0

### PR DESCRIPTION
**Pull request by stephenmogg**
Only the adoc should be updated.

### CODE REVIEW

**Comment by chabowski** [comment]
Hi Stephen, 

did you refresh your fork of the main repo before you worked on the changes? Seems there is a branch conflict, which might be due to a main fork being not up-to-date.

Thanks,
Meike

**Comment by stephenmogg** [comment]
Yes I did.

It might be one of the other two files causing the conflict.

The only one that interests me is the .adoc.

Stephen

From: Meike Chabowski ***@***.***>
Reply to: SUSE/suse-best-practices ***@***.***>
Date: Wednesday, 31 March 2021 at 15:34
To: SUSE/suse-best-practices ***@***.***>
Cc: Stephen Mogg ***@***.***>, Author ***@***.***>
Subject: Re: [SUSE/suse-best-practices] Updated cloud automation quickstart for v7.0.0 (#194)


Hi Stephen,

did you refresh your fork of the main repo before you worked on the changes? Seems there is a branch conflict, which might be due to a main fork being not up-to-date.

Thanks,
Meike

**Comment by sknorr** [comment]
@stephenmogg Unfortunately, the conflict is in the .adoc file. Without knowing the topic, it is nigh-on impossible for Meike or me to resolve in a useful way, because Git's naive attempt at merging the ifdefs does not work here.

Please also run `git rm -f .DS_Store doc` to get rid of the additional files

**Comment by stephenmogg** [comment]
Updated this morning.
I have included the fixes from @chabowski

**Comment by chabowski** [comment]
Manually merged in commit 36211af863fa43bbe07384d12055ea7e3812ec08

**Comment by chabowski** [comment]
@stephenmogg please ensure you always pull the latest updates from main before you do a commit or PR. Thank you very much. All should be fine now. But you will get another PDF also for a quick check.

**Pull request closed without merging**
