### PR TITLE
typo correction

### PR DESCRIPTION
**Pull request by pirat013**
hopefully the last change :-)
Bernd

### CODE REVIEW

**Comment by chabowski** [comment]
@pirat013: don't worry - we can easily make corrections even after publication, and it _usually_ does not take long to re-publish.

**Comment by chabowski** [comment]
@pirat013: the version the documents is based on is SLES for SAP Applications 12 SP2, isn't it? Examples are SP2, but in the documents front page we have "SLES for SAP Applicatio

**Comment by chabowski** [comment]
continuing: "SLES for SAP Applications 12 SP3" ... Just want to make sure there is no mistake in the front page.

**Comment by pirat013** [comment]
Hello Meike,

you are right. The document is based and build on SP2. I wasn't able to
find the point where we say SP3. Would you be so kind and change it to SP2.

Thanks Bernd

Warm regards
Bernd Schubert
SAP Solution Architect

Mobil: +49 173 5876798
Phone: +49 6227 752139
E-mail: bschubert@suse.com
Web: http://www.suse.com

SUSE Linux GmbH

GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG
Nürnberg) Germany

PLEASE NOTE: This e-mail may contain confidential and privileged
material for the sole use of the intended recipient.
Any review, distribution or other use by anyone else is strictly
prohibited. If you are not an intended recipient, please contact the
sender and delete all copies.
Thank you.

**Comment by pirat013** [comment]
Thanks Bernd, will do!



Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Bernd Schubert <bschubert@suse.com>
Datum: 15.11.18 17:11 (GMT+02:00)
An: reply@reply.github.com, Meike Chabowski <Meike.Chabowski@suse.com>
Betreff: Re: [SUSE/suse-best-practices] typo correction (#13)

Hello Meike,

you are right. The document is based and build on SP2. I wasn't able to
find the point where we say SP3. Would you be so kind and change it to SP2.

Thanks Bernd

Warm regards
Bernd Schubert
SAP Solution Architect

Mobil: +49 173 5876798
Phone: +49 6227 752139
E-mail: bschubert@suse.com
Web: http://www.suse.com

SUSE Linux GmbH

GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG
Nürnberg) Germany

PLEASE NOTE: This e-mail may contain confidential and privileged
material for the sole use of the intended recipient.
Any review, distribution or other use by anyone else is strictly
prohibited. If you are not an intended recipient, please contact the
sender and delete all copies.
Thank you.

**Comment by chabowski** [comment]
@pirat013: thanks for your message - will change version to SP2.

**Comment by chabowski** [comment]
@pirat013, @fmherschel latest PDF version attached. Changes are not yet committed. See title, it is now divided in Title and subtitle, to avoid the horrible hyphenation of "Linux" there, and to make it better readable. Also adjusted the Abstract on page 2.
[SLES4SAP-hana-sr-guide-PerfOpt-12-Alicloud_color_en.pdf](https://github.com/SUSE/suse-best-practices/files/2585947/SLES4SAP-hana-sr-guide-PerfOpt-12-Alicloud_color_en.pdf)

**Pull request merged**
