### PR TITLE
New setup guide SLES4SAP-hana-sr-guide-CostOpt-15.adoc

### PR DESCRIPTION
**Pull request by fmherschel**
This is the new cost-opt guide for SAPHana Sce-Up on SLE15

### CODE REVIEW

**Comment by sknorr** [comment]
Fyi, @fmherschel , the error you mailed us about is that you're defining `launchPadNotes` in your attributes file, but you had a typo when including it: `lauchPadNotes` (note the lack of the first `n`).

**Comment by fmherschel** [comment]
> Fyi, @fmherschel , the error you mailed us about is that you're defining `launchPadNotes` in your attributes file, but you had a typo when including it: `lauchPadNotes` (note the lack of the first `n`).

I noticed that (see my suse mail) however when I am searching in my sources which I used for the PR I do not have a string
lauchpadnotes (ok will try again with ignore case )...

**Comment by fmherschel** [comment]
Ok found it. Normally I always search case insensitive. Do not why this time I only searched for "lauchpad" and of course did not found it. I pushed already all commits fixing "lauch-pads" in multiple files ;-)

**Comment by sknorr** [comment]
@fmherschel Searching case-insensitive is unfortunately necessary -- AsciiDoctor always converts attribute names to lower-case in its messages and will treat all of these as the same attribute: `LaunchPadNotes` / `launchpadnotes` / `LaUnChPaDnOtEs`. I suppose, you could save yourself some trouble by lowercasing all attribute names in your source already.

**Comment by fmherschel** [comment]
@sknorr Yes was my fault! Normally I search case insensitive.

**Comment by fmherschel** [comment]
@sknorr : The first time I send my PR I got an eMail about the failed build test. Now after I have send more commits to repair the lauch vs launch problem I do not see, if the validation test runs again. In other projects I could see pending or running or finished tests, but I do not see it here.

**Comment by chabowski** [comment]
@fmherschel In former times, we used Travis CI for validation/continuous integration. Now we are working with GitHub Actions. I think you can look it up there.

**Comment by sknorr** [comment]
> @sknorr : The first time I send my PR I got an eMail about the failed build test. Now after I have send more commits to repair the lauch vs launch problem I do not see, if the validation test runs again. In other projects I could see pending or running or finished tests, but I do not see it here.

Since you are using a forked repo, apparently, you will only see runs related to this PR in your fork but not here:
https://github.com/fmherschel/suse-best-practices/actions
That seems suboptimal. I will open a bug about that, so I don't forget. My hunch is that I may not be able to do much about this and it's entirely GitHub's decision where to display validation status.

**Comment by fmherschel** [comment]
> > @sknorr : The first time I send my PR I got an eMail about the failed build test. Now after I have send more commits to repair the lauch vs launch problem I do not see, if the validation test runs again. In other projects I could see pending or running or finished tests, but I do not see it here.
> 
> Since you are using a forked repo, apparently, you will only see runs related to this PR in your fork:
> https://github.com/fmherschel/suse-best-practices/actions (but not here).
> That seems suboptimal. I will open a bug about that, so I don't forget. My hunch is that I may not be able to do much about this and it's entirely GitHub's decision where to display validation status.

@sknorr Now I could see the actions (failed and successful) at least in my fork. I in deed failed, because I searched for the validations in the "mother"-project (SUSE). I was a bit struggling, because I only have seen eMails for failed validations, but did
not got a positive status for the passed test. So I thought the test is not running. But it seams that also in this case "no news are good news" :)

**Pull request merged**
