### PR TITLE
SAP-S4HA10-setup-simplemount-sle15.adoc:  fix issue #382

### PR DESCRIPTION
**Pull request by lpinne**
Hi,

SAP-S4HA10-setup-simplemount-sle15.adoc:  fix issue #382

Regards,
Lars

### CODE REVIEW

**Comment by lpinne** [comment]
Hi,

I also added a fix for issue #292 

Regards,
Lars

**Comment by chabowski** [comment]
Hi @lpinne, the doc is not building, I am getting error messages 

```
asciidoctor: WARNING: skipping reference to missing attribute: my2node3
asciidoctor: WARNING: skipping reference to missing attribute: my2node4
```
Could you please check that first? Thank you!

**Comment by lpinne** [comment]
Hi Meike,

I changed my2Node... to my2nd...
Thank your for your patience!

Regards,
Lars

**Review by chabowski — APPROVED** [review]
Thank you @lpinne, looks good. Merging and closing.

**Pull request merged**
