### PR TITLE
seo correct editURLs l10n

### PR DESCRIPTION
**Pull request by jfaltenbacher**
SEO editurl fix master -> main

### CODE REVIEW

**Review by chabowski — APPROVED** [review]
Thank you!

**Review by sknorr — CHANGES_REQUESTED** [review]
Hi Julia,

* The corrections for the Korean documents that you made point at the English source documents (which are ADOCs). This means the URLs may work but aren't exactly correct. (~~I think that's a detail I missed in the context of the SES 6 and SLES-SAP 15 SP2 URLs today too.~~ No, those are fine.)
* could you check original documents as well please? From the root dir of the repo, try:
  `> git grep editurl | grep master | grep \.xml`
  * Edit URLs are ignored in AsciiDoc documents currently. On the other hands, those editurls don't really create any damage, so I think you can just leave them be. (Hence, excluded in the above expression.)
  * However, there are a few XML documents that still contain edit URLs pointing at `.../master/...`

**Comment by jfaltenbacher** [comment]
now all paths should be changed from master -> main

**Review by sknorr — CHANGES_REQUESTED** [review]
Thanks but...

* As I mentioned in the previous review, the Korean links are still wrong. Given the policy we applied to editurls for other translated docs, I think they should be removed entirely.
* There are a number of `/blob/` URLs here. We need `/edit/` URLs.
* Rather than change the URLs in AsciiDocs to something that is (still) wrong, please decide whether to remove them from the AsciiDocs entirely (probably simplest at this point) or to revert the changes in them.

**Comment by jfaltenbacher** [comment]
removed the editURLs from l10n files

**Comment by sknorr** [comment]
Fixed the outstanding issues (`/blob/` URLs, AsciiDoc URLs) myself & merged.

**Pull request merged**
