### PR TITLE
add "SAP S/4 HANA - Enqueue Replication 2 High Availability Cluster With Simple Mount - Setup Guide"

### PR DESCRIPTION
**Pull request by yeoldegrove**
This add the document for SLES 15 "SAP S/4 HANA - Enqueue Replication 2 High Availability Cluster With Simple Mount - Setup Guide".

Kudos to @b1tk aka. Thomas.

### CODE REVIEW

**Comment by chabowski** [comment]
@yeoldegrove thank you for the PR! I didn't know that this doc was to come ;-) - could not have a look yet due to a "heavy meeting week" but will do so on Monday.

**Comment by fmherschel** [comment]
@chabowski : This PR should not be sent to master. It is for a review for @lpinne and @fmherschel  only.

**Comment by chabowski** [comment]
@fmherschel thank you, understood :-). Just let me know when you are ready to proceed.

**Comment by fmherschel** [comment]
We need to combine this PR with additional commits still to be done. So I close this PR and we will create a new PR once we are finish to shift the document to @chabowski .

**Pull request closed without merging**
